#!/usr/bin/env sh
set -eu

usage() {
  printf 'Usage: %s add <ticket> [base] [prefix]\n' "$0" >&2
  printf '       %s remove <ticket>\n' "$0" >&2
}

die() {
  printf 'Error: %s\n' "$1" >&2
  exit "${2:-1}"
}

sanitize_ticket() {
  printf '%s' "$1" | tr -d '#[]' | tr -d '[:space:]'
}

project_root() {
  git rev-parse --show-toplevel 2>/dev/null || die "not inside a git repository" 128
}

ensure_gitignore_entry() {
  root=$1
  entry=$2
  gitignore="$root/.gitignore"

  if [ -f "$gitignore" ] && grep -qxF "$entry" "$gitignore"; then
    return 0
  fi

  printf '%s\n' "$entry" >> "$gitignore"
  printf 'Added %s to %s\n' "$entry" "$gitignore"
}

default_base_branch() {
  root=$1
  ref=$(git -C "$root" symbolic-ref --quiet --short refs/remotes/origin/HEAD 2>/dev/null) || ref=''

  if [ -n "$ref" ]; then
    printf '%s' "${ref#origin/}"
    return 0
  fi

  for candidate in main master; do
    if git -C "$root" show-ref --verify --quiet "refs/heads/$candidate"; then
      printf '%s' "$candidate"
      return 0
    fi
  done

  die "could not determine the default base branch; pass one explicitly"
}

cmd_add() {
  ticket_raw=$1
  base_arg=${2:-}
  prefix=${3:-feat}

  ticket=$(sanitize_ticket "$ticket_raw")
  [ -n "$ticket" ] || die "ticket is required"

  root=$(project_root)
  worktree_dir="$root/.worktrees/$ticket"

  if [ -e "$worktree_dir" ]; then
    printf 'EXISTS: %s (not recreated)\n' "$worktree_dir"
    return 0
  fi

  base=$base_arg
  [ -n "$base" ] || base=$(default_base_branch "$root")

  branch="$prefix/$ticket"

  ensure_gitignore_entry "$root" ".worktrees/"

  if git -C "$root" show-ref --verify --quiet "refs/heads/$branch"; then
    git -C "$root" worktree add "$worktree_dir" "$branch"
  else
    git -C "$root" worktree add -b "$branch" "$worktree_dir" "$base"
  fi

  task_file="$worktree_dir/worktree-task.md"
  project=$(basename "$root")

  cat > "$task_file" <<EOF
# Worktree Task

- Ticket: $ticket
- Branch: $branch
- Base: $base
- Project: $project

## 說明
此 worktree 是為了處理上述 ticket 而建立，請先讀取此檔案了解任務背景後再開始開發。

## 注意事項
讀完之後，如果要進行 commit，記得刪掉這個檔案（worktree-task.md），避免被一併提交進 repo。
EOF

  printf '%s\n' '---'
  printf 'WORKTREE: %s\n' "$worktree_dir"
  printf 'BRANCH: %s\n' "$branch"
  printf 'BASE: %s\n' "$base"
  printf 'TASK_FILE: %s\n' "$task_file"
}

cmd_remove() {
  ticket_raw=$1
  ticket=$(sanitize_ticket "$ticket_raw")
  [ -n "$ticket" ] || die "ticket is required"

  root=$(project_root)
  worktree_dir="$root/.worktrees/$ticket"

  [ -e "$worktree_dir" ] || die "worktree not found: $worktree_dir"

  # worktree-task.md is generated by this skill and is untracked in the branch it was
  # created from, which otherwise makes `git worktree remove` refuse the whole worktree.
  # Only this known, self-generated file is cleared — any other uncommitted work still
  # blocks removal.
  rm -f "$worktree_dir/worktree-task.md"

  git -C "$root" worktree remove "$worktree_dir"
  printf 'REMOVED: %s\n' "$worktree_dir"
}

[ "$#" -ge 1 ] || { usage; exit 64; }

action=$1
shift

case "$action" in
  add)
    [ "$#" -ge 1 ] && [ "$#" -le 3 ] || { usage; exit 64; }
    cmd_add "$@"
    ;;
  remove)
    [ "$#" -eq 1 ] || { usage; exit 64; }
    cmd_remove "$@"
    ;;
  *)
    usage
    exit 64
    ;;
esac
